name: Build Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make

      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: build/resume.pdf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
